# Update platform/gitops/applicationset-platform.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-components
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: istio-crds
        path: platform/addons/istio-crds
        syncwave: "-2"  # Install FIRST
        destinationNamespace: ""  # CRDs are cluster-scoped
      - name: istio-base
        path: platform/addons/istio
        namespace: istio-system
        syncwave: "-1"  # Install SECOND
      - name: monitoring
        path: platform/addons/observability
        namespace: istio-system
        syncwave: "0"
      - name: networking
        path: platform/addons/ingress-nginx
        namespace: ingress-nginx
        syncwave: "1"
      - name: policies
        path: platform/addons/network-policies
        namespace: polaris-apps
        syncwave: "2"
  
  template:
    metadata:
      name: '{{name}}-platform'
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncwave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mathii0402/Polaris.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true