apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: polaris-dev-services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mathii0402/Polaris.git
        revision: main
        directories:
          - path: applications/*/manifests/overlays/dev

  template:
    metadata:
      name: '{{path.basename}}-dev'
    spec:
      project: default

      source:
        repoURL: https://github.com/mathii0402/Polaris.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: polaris-apps

      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
