apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: polaris-dev-services
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mathii0402/Polaris.git
      revision: HEAD
      directories:
      - path: applications/*
  template:
    metadata:
      name: '{{path.basename}}-dev'
    spec:
      project: default
      source:
        repoURL: https://github.com/mathii0402/Polaris.git
        targetRevision: HEAD
        path: '{{path}}/manifests/overlays/dev'
      destination:
        server: https://kubernetes.default.svc
        namespace: polaris-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
