apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: polaris-data
type: Opaque
stringData:
  POSTGRES_DB: polaris
  POSTGRES_USER: polaris_user
  POSTGRES_PASSWORD: polaris_pass
