apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polaris-api
  namespace: polaris-apps
spec:
  ingressClassName: nginx
  rules:
  - host: api.polaris.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: polaris-api
            port:
              number: 8000
