apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polaris-ingress
  namespace: polaris-apps
spec:
  ingressClassName: nginx
  rules:
  - host: api.polaris.local
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: user-service-api
            port:
              number: 80
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: order-service-api
            port:
              number: 80
