apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace-labels.yaml
- install/istio-base.yaml
- install/istiod.yaml
- install/istio-ingress.yaml
- policies/default-deny.yaml
- policies/default-mtls.yaml

namespace: istio-system
