apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: polaris-apps
type: Opaque
stringData:
  DB_NAME: order_db
  DB_USER: order_user
  DB_PASSWORD: order_pass
  DB_HOST: postgres.polaris-data.svc.cluster.local
  DB_PORT: "5432"
